import { TypeOrmModuleOptions } from '@nestjs/typeorm';
import {
  AvailabilityObservationEntity,
  CommentEntity,
  DiaryCompanionEntity,
  DiaryEntity,
  DiaryLikeEntity,
  DiaryReactionEntity,
  DiaryShareEntity,
  FileCleanupJobEntity,
  ExternalContentRefEntity,
  FriendInviteEntity,
  FriendshipEntity,
  InviteCodeEntity,
  InviteUseEntity,
  MediaEntity,
  MediaFavoriteEntity,
  MediaImageEntity,
  NotificationEntity,
  NotificationPreferenceEntity,
  RecommendationExposureEntity,
  RecommendationFeedbackEntity,
  RecommendationSessionEntity,
  SpaceEntity,
  SpaceInviteEntity,
  SpaceMembershipEntity,
  UserConsentEntity,
  UserEntity,
  UserFollowEntity,
  WatchlistItemEntity,
  WatchParticipantEntity,
  WatchReactionEntity,
  WatchShareEntity,
  WatchSourceEntity,
  TransactionOutboxEntity,
} from './entities';
import { HighValueFlows1720670400000 } from './migrations/1720670400000-HighValueFlows';
import { BaseSchema1720670300000 } from './migrations/1720670300000-BaseSchema';
import { CoreRecordContract1720670500000 } from './migrations/1720670500000-CoreRecordContract';
import { FriendInvitesAndConsents1720670600000 } from './migrations/1720670600000-FriendInvitesAndConsents';
import { SpacesMembershipInvites1720670700000 } from './migrations/1720670700000-SpacesMembershipInvites';
import { WatchEventsAndPersonalReactions1720670800000 } from './migrations/1720670800000-WatchEventsAndPersonalReactions';
import { CanonicalCatalogAvailability1720670900000 } from './migrations/1720670900000-CanonicalCatalogAvailability';
import { AccountLifecycleNotificationOutbox1720671000000 } from './migrations/1720671000000-AccountLifecycleNotificationOutbox';
import { GroupRecommendationSessions1720671100000 } from './migrations/1720671100000-GroupRecommendationSessions';

export function createTypeOrmOptions(): TypeOrmModuleOptions {
  return {
    type: 'postgres',
    url: process.env.DATABASE_URL,
    host: process.env.DB_HOST ?? 'localhost',
    port: process.env.DB_PORT ? Number(process.env.DB_PORT) : 5432,
    username: process.env.DB_USERNAME ?? 'postgres',
    password: process.env.DB_PASSWORD ?? 'postgres',
    database: process.env.DB_DATABASE ?? 'davas',
    entities: [
      UserEntity,
      UserConsentEntity,
      FileCleanupJobEntity,
      UserFollowEntity,
      FriendshipEntity,
      FriendInviteEntity,
      InviteCodeEntity,
      InviteUseEntity,
      MediaEntity,
      ExternalContentRefEntity,
      AvailabilityObservationEntity,
      MediaImageEntity,
      MediaFavoriteEntity,
      WatchlistItemEntity,
      DiaryEntity,
      DiaryCompanionEntity,
      DiaryShareEntity,
      DiaryLikeEntity,
      DiaryReactionEntity,
      CommentEntity,
      NotificationEntity,
      NotificationPreferenceEntity,
      RecommendationSessionEntity,
      RecommendationExposureEntity,
      RecommendationFeedbackEntity,
      SpaceEntity,
      SpaceMembershipEntity,
      SpaceInviteEntity,
      WatchParticipantEntity,
      WatchReactionEntity,
      WatchSourceEntity,
      WatchShareEntity,
      TransactionOutboxEntity,
    ],
    migrations: [
      BaseSchema1720670300000,
      HighValueFlows1720670400000,
      CoreRecordContract1720670500000,
      FriendInvitesAndConsents1720670600000,
      SpacesMembershipInvites1720670700000,
      WatchEventsAndPersonalReactions1720670800000,
      CanonicalCatalogAvailability1720670900000,
      AccountLifecycleNotificationOutbox1720671000000,
      GroupRecommendationSessions1720671100000,
    ],
    synchronize: process.env.TYPEORM_SYNC === 'true',
    logging: process.env.TYPEORM_LOGGING === 'true',
  };
}
